In [63]:
import pandas as pd
financeData = pd.read_csv('fbc_data_2025.csv')
votingData = pd.read_csv('2024_US_County_Level_Presidential_Results.csv')

In [64]:
# Wrangles the financial dataset by taking the 10 rows for each county, averaging their values in each column, and puts the averages into a single row for each county.
# This process also reduces the number of rows for this dataset to 3143
financeDataAveraged = financeData.groupby('county_fips', as_index=False)[['Monthly Housing', 'Monthly Food', 'Monthly Transportation', 'Monthly Healthcare', 'Monthly Other Necessities', 'Monthly Childcare', 'Monthly Taxes', 'Monthly Total',
                                         'Annual Housing', 'Annual Food', 'Annual Transportation', 'Annual Healthcare', 'Annual Other Necessities', 'Annual Childcare', 'Annual Taxes', 'Annual Total',
                                         'median_family_income', 'num_counties_in_st', 'st_cost_rank', 'st_med_aff_rank', 'st_income_rank']].mean()
print(f"Number of rows and columns in financial data: {financeDataAveraged.shape}")
financeDataAveraged.head()

Number of rows and columns in financial data: (3143, 22)

,county_fips,Monthly Housing,Monthly Food,Monthly Transportation,Monthly Healthcare,Monthly Other Necessities,Monthly Childcare,Monthly Taxes,Monthly Total,Annual Housing,...,Annual Healthcare,Annual Other Necessities,Annual Childcare,Annual Taxes,Annual Total,median_family_income,num_counties_in_st,st_cost_rank,st_med_aff_rank,st_income_rank
0,1001,1316.5,876.1,1548.0,1295.2,737.9,878.2,1138.4,7789.9,15794.44840,...,15542.13558,8851.80505,10535.61214,13662.01629,93477.5104,83452.0,67.0,8.0,48.0,11.0
1,1003,1423.5,990.6,1571.5,1220.5,812.2,862.6,1212.0,8093.0,17082.00000,...,14644.38907,9746.87133,10351.86510,14544.30292,97116.7975,92918.0,67.0,2.0,59.0,4.0
2,1005,909.2,842.1,1431.7,1196.3,589.4,671.2,822.6,6462.6,10910.40000,...,14356.61277,7070.95930,8055.20472,9870.87344,77551.0166,60474.0,67.0,63.0,19.0,55.0
3,1007,939.6,800.7,1665.8,1235.5,585.4,932.4,984.2,7143.1,11272.71650,...,14823.93821,7025.80685,11188.32950,11808.59579,85717.8629,67222.0,67.0,18.0,20.0,39.0
4,1009,870.0,788.7,1652.5,1235.5,558.2,963.8,956.5,7025.5,10443.42681,...,14823.93821,6697.65267,11567.09626,11478.51394,84304.6712,76388.0,67.0,24.0,46.0,18.0

In [65]:
print(f"Number of rows and columns in voting data: {votingData.shape}")
votingData.head()

Number of rows and columns in voting data: (3160, 10)

,state_name,county_fips,county_name,votes_gop,votes_dem,total_votes,diff,per_gop,per_dem,per_point_diff
0,Alabama,1001,Autauga County,20484,7439,28190,13045.0,0.726641,0.263888,0.462753
1,Alabama,1003,Baldwin County,95798,24934,121808,70864.0,0.786467,0.204699,0.581768
2,Alabama,1005,Barbour County,5606,4158,9832,1448.0,0.570179,0.422905,0.147274
3,Alabama,1007,Bibb County,7572,1619,9241,5953.0,0.819392,0.175197,0.644194
4,Alabama,1009,Blount County,25354,2576,28115,22778.0,0.901796,0.091624,0.810173

In [66]:
# Confirms the use of county_fips as the unit of observation.
print(f"Number of unique counties in financial data: {len(financeDataAveraged['county_fips'].unique())}")
print(f"Number of unique counties in voting data: {len(votingData['county_fips'].unique())}")

Number of unique counties in financial data: 3143
Number of unique counties in voting data: 3160

In [67]:
# Gets the types of variables and non-null counts for the financial data.
financeDataAveraged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3143 entries, 0 to 3142
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   county_fips                3143 non-null   int64
 1   Monthly Housing            3143 non-null   float64
 2   Monthly Food               3143 non-null   float64
 3   Monthly Transportation     3143 non-null   float64
 4   Monthly Healthcare         3143 non-null   float64
 5   Monthly Other Necessities  3143 non-null   float64
 6   Monthly Childcare          3143 non-null   float64
 7   Monthly Taxes              3143 non-null   float64
 8   Monthly Total              3143 non-null   float64
 9   Annual Housing             3143 non-null   float64
 10  Annual Food                3143 non-null   float64
 11  Annual Transportation      3143 non-null   float64
 12  Annual Healthcare          3143 non-null   float64
 13  Annual Other Necessities   3143 non-null   float64
 14  Annual Childcare           3143 non-null   float64
 15  Annual Taxes               3143 non-null   float64
 16  Annual Total               3143 non-null   float64
 17  median_family_income       3131 non-null   float64
 18  num_counties_in_st         3143 non-null   float64
 19  st_cost_rank               3143 non-null   float64
 20  st_med_aff_rank            3131 non-null   float64
 21  st_income_rank             3131 non-null   float64
dtypes: float64(21), int64(1)
memory usage: 540.3 KB

In [68]:
# Cleans the data by dropping any rows with null values. This is necessary since the info function above showed that some rows have null values.
financeDataAveraged = financeDataAveraged.dropna()
financeDataAveraged.shape

(3131, 22)

In [69]:
# Gets the types of variables and non-null counts for the voting data.
votingData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3160 entries, 0 to 3159
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   state_name      3160 non-null   object
 1   county_fips     3160 non-null   int64
 2   county_name     3160 non-null   object
 3   votes_gop       3160 non-null   int64
 4   votes_dem       3160 non-null   int64
 5   total_votes     3160 non-null   int64
 6   diff            3160 non-null   float64
 7   per_gop         3160 non-null   float64
 8   per_dem         3160 non-null   float64
 9   per_point_diff  3160 non-null   float64
dtypes: float64(4), int64(4), object(2)
memory usage: 247.0+ KB

In [70]:
# Gets the summary statistics for the financial data.
financeDataAveraged.describe()

,county_fips,Monthly Housing,Monthly Food,Monthly Transportation,Monthly Healthcare,Monthly Other Necessities,Monthly Childcare,Monthly Taxes,Monthly Total,Annual Housing,...,Annual Healthcare,Annual Other Necessities,Annual Childcare,Annual Taxes,Annual Total,median_family_income,num_counties_in_st,st_cost_rank,st_med_aff_rank,st_income_rank
count,3131.000000,3131.000000,3131.000000,3131.000000,3131.000000,3131.000000,3131.000000,3131.000000,3131.000000,3131.000000,...,3131.000000,3131.000000,3131.000000,3131.000000,3131.000000,3131.000000,3131.000000,3131.000000,3131.000000,3131.000000
mean,30429.768764,1152.249920,873.211626,1555.668093,1285.752922,681.480773,967.087512,1023.640115,7539.096008,13827.013447,...,15429.221234,8177.749523,11604.979656,12283.676388,90469.159938,82714.867135,96.558927,48.778665,48.688279,48.688279
std,15144.633478,365.745147,92.796394,136.432153,226.553338,143.626061,334.353285,308.036186,1115.398393,4388.930456,...,2718.659256,1723.484974,4012.162484,3696.452679,13384.785788,20074.548603,56.793359,43.025558,42.814481,42.814462
min,1001.000000,577.700000,664.400000,534.500000,848.400000,450.600000,293.800000,553.500000,5937.100000,6932.708780,...,10180.809160,5408.353530,3525.879860,6642.366360,71245.080400,34894.000000,1.000000,1.000000,1.000000,1.000000
25%,19006.000000,943.000000,813.000000,1474.700000,1134.300000,596.550000,751.300000,830.000000,6847.250000,11315.249595,...,13612.541200,7157.613300,9016.564480,9958.314975,82166.930100,70035.500000,64.000000,18.000000,18.000000,18.000000
50%,29183.000000,1011.200000,856.800000,1549.600000,1239.700000,629.400000,912.200000,959.200000,7283.100000,12134.400000,...,14877.570320,7552.110620,10943.331020,11510.662540,87396.813100,80333.000000,87.000000,39.000000,39.000000,39.000000
75%,45082.000000,1213.450000,910.300000,1640.150000,1385.000000,711.000000,1119.100000,1124.600000,7910.500000,14561.400000,...,16621.825950,8532.089970,13430.672220,13494.566505,94925.409300,92500.000000,105.000000,66.000000,66.000000,66.000000
max,56045.000000,4215.000000,1920.400000,2481.200000,2161.900000,1804.500000,3366.200000,3835.400000,17009.900000,50580.000000,...,25943.290470,21656.236800,40396.737400,46023.879300,204117.596100,211445.000000,254.000000,254.000000,252.000000,252.000000

In [71]:
# Gets the summary statistics for the voting data.
votingData.describe()

,county_fips,votes_gop,votes_dem,total_votes,diff,per_gop,per_dem,per_point_diff
count,3160.000000,3.160000e+03,3.160000e+03,3.160000e+03,3.160000e+03,3160.000000,3160.000000,3160.000000
mean,30239.310759,2.446038e+04,2.373631e+04,4.900751e+04,7.240696e+02,0.666288,0.319992,0.346296
std,15242.172167,5.638631e+04,8.339599e+04,1.388659e+05,4.224130e+04,0.160195,0.157975,0.318077
min,1001.000000,8.600000e+01,6.000000e+00,9.700000e+01,-1.227247e+06,0.050812,0.035088,-0.866782
25%,18150.500000,3.708000e+03,1.199750e+03,5.277750e+03,1.063750e+03,0.577375,0.197090,0.168269
50%,29158.000000,8.304000e+03,3.458500e+03,1.238750e+04,3.404000e+03,0.700416,0.285080,0.416269
75%,45071.500000,2.119625e+04,1.173625e+04,3.399350e+04,8.234000e+03,0.790141,0.409024,0.593323
max,56045.000000,1.189862e+06,2.417109e+06,3.728427e+06,1.396870e+05,0.959649,0.917963,0.924561

In [74]:
# Merges the two datasets together on the county_fips unique column.
combinedData = votingData.merge(financeDataAveraged, how='inner', on='county_fips')
combinedData.head()

,state_name,county_fips,county_name,votes_gop,votes_dem,total_votes,diff,per_gop,per_dem,per_point_diff,...,Annual Healthcare,Annual Other Necessities,Annual Childcare,Annual Taxes,Annual Total,median_family_income,num_counties_in_st,st_cost_rank,st_med_aff_rank,st_income_rank
0,Alabama,1001,Autauga County,20484,7439,28190,13045.0,0.726641,0.263888,0.462753,...,15542.13558,8851.80505,10535.61214,13662.01629,93477.5104,83452.0,67.0,8.0,48.0,11.0
1,Alabama,1003,Baldwin County,95798,24934,121808,70864.0,0.786467,0.204699,0.581768,...,14644.38907,9746.87133,10351.86510,14544.30292,97116.7975,92918.0,67.0,2.0,59.0,4.0
2,Alabama,1005,Barbour County,5606,4158,9832,1448.0,0.570179,0.422905,0.147274,...,14356.61277,7070.95930,8055.20472,9870.87344,77551.0166,60474.0,67.0,63.0,19.0,55.0
3,Alabama,1007,Bibb County,7572,1619,9241,5953.0,0.819392,0.175197,0.644194,...,14823.93821,7025.80685,11188.32950,11808.59579,85717.8629,67222.0,67.0,18.0,20.0,39.0
4,Alabama,1009,Blount County,25354,2576,28115,22778.0,0.901796,0.091624,0.810173,...,14823.93821,6697.65267,11567.09626,11478.51394,84304.6712,76388.0,67.0,24.0,46.0,18.0

In [77]:
# Checks that the shape is correct. It should have 31 columns.
# 31 columns comes from 22 columns from the financial data plus 10 columns from the voting data minus 1 common column (county_fips).
# 3104 rows is slightly less than the 3131 and 3160 of the two datasets, but this is intentional as only rows that had their county_fips exist in both datasets were merged.
combinedData.shape

(3104, 31)

In [78]:
# Checks that every county_fips value is unique.
print(f"Number of unique counties in combined data: {len(combinedData['county_fips'].unique())}")

Number of unique counties in combined data: 3104